[colors.primary]
background = "#0f1c1e" # "#1e2330"

[font]
normal.family = "Courier Nerd Font"
size = 16

[keyboard]
bindings = [
   { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window]
opacity = 0.90
